import React, { Component } from 'react'

export default class DogImage extends Component {
    constructor(props) {
        super(props);
        this.state = {
            imageURL: ''
        }
    }

    getNewDog() {
        fetch('https://dog.ceo/api/breeds/image/random')
            .then(res => res.json())
            .then(data => {
                this.setState({ imageURL: data.message });
            })
    }

    handleClick = () => {
        this.getNewDog();
    }
    componentDidMount() {
        this.getNewDog()
    }
    render() {

        return (
            <div onClick={this.handleClick}>
                <img src={this.state.imageURL} width="300px" alt="random dog generated by Dog.ceo API"></img>
            </div>
        )
    }
}
